// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewWebApplication2.Data;

#nullable disable

namespace NewWebApplication2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250120154733_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewWebApplication2.Models.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 50m,
                            Code = "ET001",
                            Name = "Type A"
                        },
                        new
                        {
                            Id = 2,
                            Area = 100m,
                            Code = "ET002",
                            Name = "Type B"
                        },
                        new
                        {
                            Id = 3,
                            Area = 10m,
                            Code = "ET003",
                            Name = "Type C"
                        },
                        new
                        {
                            Id = 4,
                            Area = 15m,
                            Code = "ET004",
                            Name = "Type D"
                        },
                        new
                        {
                            Id = 5,
                            Area = 80m,
                            Code = "ET005",
                            Name = "Type I"
                        },
                        new
                        {
                            Id = 6,
                            Area = 66m,
                            Code = "ET006",
                            Name = "Type F"
                        },
                        new
                        {
                            Id = 7,
                            Area = 150m,
                            Code = "ET007",
                            Name = "Type G"
                        },
                        new
                        {
                            Id = 8,
                            Area = 30m,
                            Code = "ET008",
                            Name = "Type H"
                        });
                });

            modelBuilder.Entity("NewWebApplication2.Models.PlacementContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductionFacilityId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("ProductionFacilityId");

                    b.ToTable("PlacementContracts");
                });

            modelBuilder.Entity("NewWebApplication2.Models.ProductionFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("StandardArea")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductionFacilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PF001",
                            Name = "Facility 1",
                            StandardArea = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Code = "PF002",
                            Name = "Facility 2",
                            StandardArea = 3000m
                        },
                        new
                        {
                            Id = 3,
                            Code = "PF003",
                            Name = "Facility 3",
                            StandardArea = 2000m
                        },
                        new
                        {
                            Id = 4,
                            Code = "PF004",
                            Name = "Facility 4",
                            StandardArea = 2500m
                        },
                        new
                        {
                            Id = 5,
                            Code = "PF005",
                            Name = "Facility 5",
                            StandardArea = 8000m
                        },
                        new
                        {
                            Id = 6,
                            Code = "PF006",
                            Name = "Facility 6",
                            StandardArea = 10000m
                        },
                        new
                        {
                            Id = 7,
                            Code = "PF007",
                            Name = "Facility 7",
                            StandardArea = 1000m
                        });
                });

            modelBuilder.Entity("NewWebApplication2.Models.PlacementContract", b =>
                {
                    b.HasOne("NewWebApplication2.Models.EquipmentType", "EquipmentType")
                        .WithMany("PlacementContracts")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewWebApplication2.Models.ProductionFacility", "ProductionFacility")
                        .WithMany("PlacementContracts")
                        .HasForeignKey("ProductionFacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquipmentType");

                    b.Navigation("ProductionFacility");
                });

            modelBuilder.Entity("NewWebApplication2.Models.EquipmentType", b =>
                {
                    b.Navigation("PlacementContracts");
                });

            modelBuilder.Entity("NewWebApplication2.Models.ProductionFacility", b =>
                {
                    b.Navigation("PlacementContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
